### ISSUE TITLE
Gene (and others) Ontology

### ISSUE THREAD

**Issue by schae234** [schae234/Camoco#10]
### Comparing different networks
We already have the COB.compare_degree method to give us a gut check on whether or not two networks are different or not, but this does not give us a check on which network is "better". When we construct a network, there are a couple of key things that we always want to check to make sure that the network is "good", aka getting a bead on the functional information that either is or isn't in the network. Sure we can compare degrees,  but what does this really tell us in terms of things functionally? (what we ultimately care about)

## Thank jibbers for gold standards
**If** there is functional information contained in a network, then we should see that reflected in the gold standard. We can use this as a gut check for whether or not making subtle changes in the network changes whatever functional information is encoded in it. 

## The goal
Whenever we build a network, one of the first things we should do is cross reference whether or not it captures gold standard functional information.

## Tasks

+ Build ontology classes from Gene ontology OBO data and GO term assignments from maize sequence ftp site.

+ Add method to Ontology class which accepts a COB class and iterates through its terms, returning the appropriate `COB.density` measure for each term. 
    + Add needed kwargs to make this generalizable, i.e. min and max sizes for term for inclusion in density measure (large gene sets load a large part of network and take a lot of resources)
    + Make reasonable choices for mapping term loci to COB.refgen loci

+ Add Ontology for MapMan terms see [this] paper(http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0099193) for more info on MapMan gold standard and where to download it.

**Comment by schae234** [comment]
Once you have a solution for building GO Ontologies, we should use the the ontology you built to do a cross reference against a (any) network. You are right asking about building a 'separate' network from the ontology terms, but the way we do it is sort of round about.

You can think of an Ontology term as a sort of pre-built network, nodes are genes and edges are binary and represent whether or not two genes are within the same term (they are co-annotated) and this is done on a term by term basis (treating terms independently being a good idea is another question we might get into later...). So a set of three genes within a single Term are each fully connected to one another and not connected to anything else. The question is are these genes also strongly connected in the COB object? 

We talked a bit on hangouts on whether we should approach this using the ontology term as an anchor or to use the COB term as an anchor, but now that I think about it, maybe we should just start a new class so we don't require either class to rely on the other. 

Create a new class that is created from a COB object and an Ontology object. Then add a method that calculates concordance between the two objects by iterating over the class and calculating density for each term. We can add statistics after that, as I said before, the COB class has internal access to its RefGen which has a `random_gene()` method which you can use to quickly get density between a random set of genes the same size as the genes in the term.

### Tasks
+ Create a new class that compares COBs and Ontologies
+ Add a method that calculates density and p-values between genes within terms.

**Comment by schae234** [comment]
Hey Joe,

I have some scripts in the bin dir which kind of outline this sort of "report" style class I have in my head. I don't really have all the details hammered out yet, hence why they are one off scripts and not classes. 

You can decide what you think is best first pass, but I think am thinking something of an API that looks kind of like:
```
from camoco import Config as cf

class Report(Object):
    # I dont know if we want to inherit from Camoco or not
    # It does have convenience methods for temp files and the such
    
    def __init__(self,cob,ontology):
        pass

    ''' Private Methods '''
    def _generate(self):
        pass

    ''' Output methods '''
    def to_md(self):
        pass
    def to_pdf(self):
        pass
    def to_html(self):
        pass
```  

Just thinking

**Comment by monprin** [comment]
So would this become more or less the primary command line interface with the camoco library?

**Comment by schae234** [comment]
Closing this due to recent pull requests. #13  and #14
