### ISSUE TITLE
MCL requirement

### ISSUE THREAD

**Issue by schae234** [schae234/Camoco#15]
Right now MCL is required to be installed and we have no way to check if it is installed. We either need a check or a fall-back plan.

**Comment by monprin** [comment]
Agreed, but maybe in the morning... Or you know, during the week.

**Comment by schae234** [comment]
Come on this is prime time Joe!

**Comment by schae234** [comment]
If you are drunk right now, just hash tag it in your commit message.

**Comment by monprin** [comment]
Not drunk, github and alcohol don't mix (well maybe, see: Ballmer Peak http://xkcd.com/323/ ) also found a really cool github Android app.

**Comment by schae234** [comment]
This is now handled in the `.travis.yml` file. It still does not error out gracefully if MCL isn't installed.
