### ISSUE TITLE
To Rectify libicui18n.so.48 Import Error

### ISSUE THREAD

**Issue by monprin** [schae234/Camoco#16]
The basic answer is to install the package which creates this, but that requires root, here is the non-root version:

1.  Download source from: http://packages.ubuntu.com/source/precise/icu
    (if you are not on precise, use replace the name, but this will download a different version, this may be rectified by reinstalling apsw in order to recognize the new version, but this is untested)
2.  Unpack it and navigate to ` .../icu/source`
3.  Set the install directory: `$ ./configure --prefix=/path/to/local/installs/`
     (make sure this folder is in your `LD_LIBRARY_PATH` variable)
4.  `$ make`
5.  `$ make install`

That should install the necessary library.

**Comment by schae234** [comment]
so this lets you run camoco from any of the lab machines, without re-PIPing everything?
