### ISSUE TITLE
Retrieve all ontology terms associated with loci

### ISSUE THREAD

**Issue by monprin** [schae234/Camoco#38]
It would be handy to do a "reverse" lookup for genes to ontology terms, and for GO, possibly even have cutoffs for how big or small a term can be before reporting it. I would implement it myself but I don't have a great feeling for how this would best integrate with code style already in ontology.

**Comment by schae234** [comment]
Added here: https://github.com/schae234/Camoco/blob/49be8cad5c84ea6c1a6afe534053c025d4e8d249/camoco/Ontology.py#L92

**Comment by schae234** [comment]
🎆 📯 🎺 🎊 💯 🥇
