### ISSUE TITLE
Update on feather?

### ISSUE THREAD

**Issue by schae234** [schae234/Camoco#43]
Feather is on 0.9.0 now, has this solved our previous issues with it?

**Comment by monprin** [comment]
Well it would appear that feather is now 0.3.1 in the repo, where did you see 0.9.0? and it does appear based on the repo that this point release fixed the issue, but I still have to test it and will do so before the end of the year.

**Comment by schae234** [comment]
Ok, so the person I was helping was trying `pip install feather` which is a different package and is at v0.9.0. Still a good idea to check on this constrain though.

**Comment by schae234** [comment]
Feather was removed from Camoco.
