### ISSUE TITLE
Networks from different count metrics

### ISSUE THREAD

**Issue by schae234** [schae234/Camoco#6]
Our pipeline currently consists of three major components:

+ [NGS read mapping and creating BAMs](https://github.com/schae234/pypeline)
+ [Converting reads to counts (FPKM)](https://github.com/schae234/MixedHTSeq)
+ [Building and analysing coexpression networks](https://github.com/schae234/Camoco)

The first part in making BAMs is pretty set in stone, we are **not** going to go back and change any of this sparing a major quality incident. 

The second chunk is the most recent with us having to go back and tear out cufflinks for our own read counting mechanism. 

The final part is where the majority of the analysis has been. This is the most plastic portion and the part we are actively working on the most. One of our questions has been, how much do our results rely on the previous parts of the pipeline. We have gone with reasonable decisions making these networks, but we wonder if we built them using a different metric, would the network connectivity change drastically?

#### Task 1: Rebuild our vanilla COB class
Install camoco on whatever computer and build a COB instance using an FPKM table generated as output from mixedHTSeq. You will need to build a couple of other camoco classes, mainly the RefGen class using the longest transcript gff files we talked about

#### Task 2: `compare_degree` COB method
We need a way to compare one COB instance to another COB instance. Write a method in the COB class that takes in another COB class. The method should iterate over the genes in the instance and compare the degree (number of significant network interactions) of the gene in instance A to instance B. We can talk more about what statistic to use here, but for right now just plan on returning a pearson correlation for the two degree vectors.

#### Task 3: Build a COB using canonical genes
Download gene annotations from [here](http://ftp.maizesequence.org/release-5b/) and recreate a gff using gene intervals which are labeled as canonical. Re-run mixedHTSeq on this new GFF file and build a COB instance using canonical genes. Compare the longest transcript COB instance to the canonical COB instance.

**Comment by schae234** [comment]
##Add one:
+ Make report with biggest changes between the longest_transcript and the is_canocical.

**Comment by monprin** [comment]
All tasks here completed, pull requests have been made to Camoco and mixedHTseq to add them in.
