### ISSUE TITLE
Get TravisCI working for OSX

### ISSUE THREAD

**Issue by schae234** [schae234/Camoco#68]
Camoco was developed on linux, but it should be able to be easily ported to OSX. We should ensure all the installation scripts work on OSX and then add continuous integration for OSX on TravisCI. 

# Objectives
- [x] add code to allow installation on OXS
- [x] modify `.travis.yml` to include CI for OSX

**Comment by seraco** [comment]
I develop on OSX, so I will try to fix this issue.

**Comment by schae234** [comment]
@seraco that would be great! 👍

**Comment by schae234** [comment]
I meant to include this on the original issue, but #65 references this issue and has a traceback containing an error log.

**Comment by seraco** [comment]
#71 However, there is more work to do. Now I realize that some tests are not passed because I skipped the installation of some modules, which were not necessary for the general installation, but that are used in the tests.

**Comment by schae234** [comment]
This looks good. Let me know when you are satisfied with #71 and I will merge it. It looks like there was 1 regression bug that failed for python V3.5, but I think that could be the fault of a bad test case, which is a different issue completely.

**Comment by seraco** [comment]
I am satisfied 😀

**Comment by schae234** [comment]
Thanks @seraco for adding this! Great work! 🎺
