### ISSUE TITLE
Add a coveralls badge to readme

### ISSUE THREAD

**Issue by schae234** [schae234/Camoco#70]
Add the necessary code to `.travis.yml` and `setup.py` to install the `py.test-cov` package and make the appropriate `coveralls` call in Travis to generate a [coveralls.io](https://coveralls.io/) badge.

### Note:
This might require some github magic on my part, i.e. allowing coveralls.io to read from the camoco repo. Contact me and we can work it out together.

**Comment by fuzzmz** [comment]
Hey @schae234, I'd like to work on this, can you assign me to it?

**Comment by schae234** [comment]
Hi @fuzzmz, we would love your help 👍 

We are currently using the assignees in github internally for our laboratories projects. But I can merge pull requests if you open them with changes.

**Comment by fuzzmz** [comment]
Awesome. I'll get to it.

-- Serban Constantin

**Comment by schae234** [comment]
This was added in #72
